version: "3.9"  
services:
  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "M1st2rPassw0rd!"
      MSSQL_PID: Express
    ports: 
      - "14333:1433"
      
  api:
    hostname: api
    image: maurobernal/microservices-api:latest
    depends_on:
      - mssql
    ports: 
    - "8080:80"
    